name: Build

on:
  - push
  - pull_request

jobs:
  docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set sample production environment variables
        run: |
          echo "VITE_API_URL=http://example.com" >> .env.production
          echo "DB_FILE=some.db" >> .env.production
          echo "JWT_SECRET=some-secret" >> .env.production

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mecanojob-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/image.tar

      - name: Check Docker image size
        run: |
          docker load --input /tmp/image.tar
          echo "Docker image details:"
          docker images mecanojob-test:latest
